name: Release

on: create

jobs:
  releaseJob:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/releases'
      env:
        VERSION: 0
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Build and Create a PR
          uses: technote-space/create-pr-action@v2
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            EXECUTE_COMMANDS: |
              VERSION=$(cat package.json | grep version | head -l | awk '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
              npm ci
              tsc
              sed -i 's/# UNRELEASED.*/# UNRELEASED\n\n# '$VERSION'/g' CHANGELOG.md
            COMMIT_MESSAGE: 'creating a release-X.X.X branch'
            #COMMIT_NAME: 'GitHub Actions'
            #COMMIT_EMAIL: 'example@example.com'
            PR_BRANCH_NAME: format('{{release-{0}}}', VERSION')
            PR_TITLE: 'clean up changelog'
            
        - name: Delete branch
          uses: dawidd6/action-delete-branch@v3
          with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            branches: release