name: Release

on: create

jobs:
  releaseJob:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    env:
      VERSION: 0
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Build and Update CHANGELPG
        run: |
            VERSION=$(cat package.json | grep version | head | awk '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
            npm ci
            tsc
            sed -i 's/# UNRELEASED.*/# UNRELEASED\n\n# '$VERSION'/g' CHANGELOG.md
      - name: Make New Tagged Release Branch and PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: join(['release-', $VERSION])
          commit-message: 'Update CHANGELOG'
          base: 'master'
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branches: release
